name: 🐛 Баг
title: '[баг] '
description: Report a bug
labels: ['type: bug', 'status: needs triage']

body:
  - type: markdown
    attributes:
      value: |
        ## Перед написанием Issue
        1. Проверьте что в [Issues](http://github.com/flowseal/zapret-discord-youtube/issues?q=is%3Aissue) нет Issue подобного вашему.
        2. Make sure `rustc` and all relevant Tauri packages are up to date.
        3. Make sure it's an issue with Tauri and not something else you are using.
        4. Remember to follow our community guidelines and be friendly.

  - type: textarea
    id: description
    attributes:
      label: Опишите вашу проблему
      description: Чётко опишите проблему с которой вы столкнулись
      placeholder: Описание проблемы
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Шаги воспроизведения проблемы
      description: Шаги по воспроизведению поведения (вашей проблемы).
      placeholder: |
        Напишите здесь шаги, с помощью которых можно повторить вашу проблему
        на других компьютерах

  - type: textarea
    id: expected-behavior
    attributes:
      label: Ожидаемое поведение
      description: Какое поведение программы вы ожидаете?

  - type: textarea
    id: bat-name
    attributes:
      label: Какой .bat файл вы используете?
    validations:
      required: true

  - type: textarea
    id: other-bat
    attributes:
      label: Использовали ли вы другие .bat?
      description: Пробовали ли вы использовать другой .bat для устранения проблемы? Если использовали, то какие?
    validations:
      required: true

  - type: textarea
    id: additions
    attributes:
      label: Дополнительные детали
